# Generated by Django 5.1.3 on 2024-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='Departamentos'),
        ),
    ]
