# Generated by Django 5.1.3 on 2024-11-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamentos_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={'ordering': ['name'], 'verbose_name_plural': 'Departamento'},
        ),
        migrations.AlterUniqueTogether(
            name='departamentos',
            unique_together={('name', 'short_name')},
        ),
    ]
